#spring:
#  mvc:
#    static-path-pattern: /res/**
#  web:
#    resources:
#      static-locations: [classpath:/test/ , classpath:/static/]
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
